### ISSUE TITLE
[IMP] AFC-1522 hr_departments_partner

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#459]
![image](https://user-images.githubusercontent.com/9428370/101243352-1104ff80-3700-11eb-99b5-bc8869426c20.png)

![image](https://user-images.githubusercontent.com/9428370/101243431-938dbf00-3700-11eb-92f6-c3024ca1bdec.png)

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-hr/tree/Dev-12.0-Fenix_Sprint-02/hr_departments_partner

**Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Description to the manifest:** 
Adds street address to Departments

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 25mins

**Comment by iammiracle** [comment]
[PR Created](https://github.com/vertelab/odoo-hr/pull/32) - This means you cant add more than one address to department

![image](https://user-images.githubusercontent.com/7355805/101246791-c42c2380-3715-11eb-91a8-1233381e8a8c.png)

![image](https://user-images.githubusercontent.com/7355805/101246795-d1e1a900-3715-11eb-8666-1947ebbbd30b.png)

**Comment by FredrikArvas** [comment]
Ok, 
I did not think of that limitation. But, let's keep it like this for now. If we need more addresses per department, we can figure out a new solution!

Thanks

(Please add your time)

**Comment by FredrikArvas** [comment]
Hi again @iammiracle 
We bumped into trouble with the limitations of departments only to be linked to one address!
So priority is now: 
1 Departmetns can have multiple adresses.
2 Show address-info (in some form) in the tree-view and the kanban-view.
Ideas: 
Show adressfield with the "tag-widget" in the tree-view
Show the address in the kanban-view if it is one, if it multiple, show each city, or show a number of adresses or the text "Multiple locations" or ...

**Comment by iammiracle** [comment]
@FredrikArvas let me be sure, I understand you well.

Formview: You want me to make add the address field and make it accept multiple "res.partners" as displayed as "tags",
Kanban: then you want details of the address to show if there is one address in the field and hide the details fields when the addresses are more than 1.

If the address in the department is one, the details of the address should show on form view, tree and kanban view, = yes.
kanbanview: but if more than 1 address, it should show "Multiple locations", or something else that works.

The details of the addresses will be street, city, state, zip and country, when possible, otherwise, something else.

Make an attempt with what is easiest first and show screenshots.

**Comment by iammiracle** [comment]
@FredrikArvas any comment on this?

**Comment by FredrikArvas** [comment]
@iammiracle I am sorry for not having responded earlier. I simply missed that you were waiting. Please proceed if this is clear.

Here is a revised text: 
If the address in the department is one, the details of the address should show on form view, tree and kanban view, = yes.
If more than 1 address, it should show the addresses (and for Kanbanview nothing or something that works).
The details of the addresses will be street, zip city, state, and country, when possible, otherwise, something else.

**Comment by iammiracle** [comment]
@FredrikArvas i have made the changes. [See PR](https://github.com/vertelab/odoo-hr/pull/44)

**Comment by arturchilangwa-vertel** [comment]
@FredrikArvas PR https://github.com/vertelab/odoo-hr/pull/44 is now merged.
