### ISSUE TITLE
[IMP] AFC-1406b api_odoo_xmlrpc

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#468]
**Userstory:** 
1 Add a config-description in the /static/index.html-file
![image](https://user-images.githubusercontent.com/9428370/101733181-bf24f680-3abe-11eb-88c1-9575a5b42b23.png)
![image](https://user-images.githubusercontent.com/9428370/101733257-d8c63e00-3abe-11eb-82b3-b5246e7440e3.png)

Please explain how I filter out: 
res.partner=1 (the main company)
res.user=1 (the admin)
hr.employee=1 (the admin)
from beeing syncronized between databases

2 Add a "Hello world"-test-command to check if the connection between the two servers is up
![image](https://user-images.githubusercontent.com/9428370/101728348-93057780-3ab6-11eb-9c8d-0c279cde6b8a.png)

**Module name:** (added by Nils or Fredrik)
https://github.com/vertelab/odoo-api/tree/Dev-12.0-DAFA-Sprint-02/api_odoo_xmlrpc

**Development Branch name:** 
Dev-12.0-DAFA-Sprint-02-AFC-1406b-api_odoo-xmlrpc

**Target Branch name:** 
https://github.com/vertelab/odoo-api/tree/Dev-12.0-DAFA-Sprint-02/api_odoo_xmlrpc

**Test-steps:**
Install the module api_odoo_xmlrpc
Login with admin/admin
Click settings -> Global settings -> Sycronized items

**Test-data:**

**Description to the manifest:** 
This update adds description and limits the sync of system-unique-records (like base.company and base.admin)

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 4 Hours and 20 mins

**Comment by FredrikArvas** [comment]
@rupareliyahemangi145 
Could you please assist me in testing this module on our servers?
I have trouble with the connections:
![image](https://user-images.githubusercontent.com/9428370/101733769-a23cf300-3abf-11eb-8560-36ca5ff71f4e.png)
I am available in 45 minutes now

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas and @Radhika435 

Can you please share credential of both servers or Databases?

**Comment by FredrikArvas** [comment]
Both servers are inside the clients network.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas No problem

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas  and @Radhika435 

I've create PR https://github.com/vertelab/odoo-api/pull/9 to test connection.

Here is video link: https://www.loom.com/share/bb53cc23b1494547a9dc814d0b827c28

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
did you include these items?

Please explain how I filter out:
- res.partner=1 (the main company)
- res.user=1 (the admin)
- hr.employee=1 (the admin)
from beeing syncronized between databases

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

We can't add demo data as server is required in that. Let me create index file. I will explain this in index file.

**Comment by FredrikArvas** [comment]
Thanks!
The reason for the post is that these data are always created in each database (hmm, not the hr.employee). 
I think I want a python-code exclusion of these records. But please suggest a solution.

**Comment by rupareliyahemangi145** [comment]
Yes these data are always in each database.

You mean you don't want to sync this data?

You need to add domain in Synchronized Objects(Setting >> General Setting >> Configuration Synchronization >> Object to be Synchronized).

Domain is technical but let me explain how can add domain. Otherwise how need to configure servers and objects I already explained in videos and to Radhika.

Value(Data) in domain field must be in list([]).

For e.g.
1. If you don't want to sync employee record which has id(Technical field of Employee) 1.
Then need to add data like, [('id', '!=', 1)].
[(<technical_field_name>, <operator(=, !=, in, ilike)>, <value>)]

2. Suppose you want to sync only Job seeker(res.partner). So you have added one flag **job_seeker** inside res.partner.
Need to use that field in domain.
[('job_seeker', '=', True)]

Please check it and let me know if need to prepare example with screenshot in index file.

Thanks.

Regards,
Hemangi.
