### ISSUE TITLE
AFC-1183 - Add an archive button to an outplacement

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#552]
**Userstory:** 
As a user, I want archive an outplacement-object. 

1 Add a field in Outplacement Final report tab when the Final Report is approved. 
Populate the field from here: 
https://github.com/vertelab/odoo-outplacement/blob/4a9ad21206d6d392dfacefde774a62039efafef5/outplacement_final_report_mq_ipf/models/outplacement.py#L188 

Place the field here:
![image](https://user-images.githubusercontent.com/61729317/119952994-d50b7280-bf9d-11eb-9195-f0a12cb33a9d.png)

When this field has a vaule, display the button.
Please add the normal smart-button to the outplacement-module-form-view

**Screen-shots with changes:** (illustration of proposed changes)
![image](https://user-images.githubusercontent.com/61729317/116985090-4d975000-accc-11eb-84dc-326eef8d912b.png)
**Module name:** (added by Nils or Fredrik)
odoo-outplacement/outplacment

**Development Branch name:** 
Dev-12.0-DAFA-AFC-1183_archive-button.

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02

**Test-steps:**
Install the module...
Login with...
Click...

**Test-data:**

**Description to the manifest:** 
This version adds an archive-button

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 50 mins

**Comment by fredrikarvas-vertel** [comment]
@SebastianGieser-Vertel - Do you know where we have information in DAFA about an approved Final Report?
I would like a state-changed or a Approved Date.

**Comment by SebastianGieser-Vertel** [comment]
Currently the only indication is a chatter message.

https://github.com/vertelab/odoo-outplacement/blob/4a9ad21206d6d392dfacefde774a62039efafef5/outplacement_final_report_mq_ipf/models/outplacement.py#L188

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/224 for this issue.
Added **Final report Approve date** field and **Archive** button inside **outplacement_final_report** module because **Final report** tab is added by this module and **Archive** button is depends on **Final report approve date** field.

Filled value in Final report approve date field after message_post.
![final_report_approve_date](https://user-images.githubusercontent.com/36560391/119974790-bffd0680-bfd2-11eb-8af0-9f91b2e19742.png)

I can't test **Final report Approve date** with server configuration but I've tested Archive button by adding manual date.
https://www.loom.com/share/a1a39c7317c84466bd30362c5e4d993b

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I think I have to create new PR for instead of this PR https://github.com/vertelab/odoo-outplacement/pull/224 after you merger this PR https://github.com/vertelab/odoo-outplacement/pull/222.

Because PR#222 contain changes of outplacement_final_report_mq_ipf module and my PR#224 also contain changes of outplacement_final_report_mq_ipf module.

It will create conflict if merge both. Please let me know if you find conflict, I will create new PR after merger of PR#222.

**Comment by fredrikarvas-vertel** [comment]
This is correct. 
If you make a note on PR#224 that it can not be merged before PR#222 that is enough.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas
