### ISSUE TITLE
AFC-2406 - IMP Interpreter Accountant View

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#614]
**Userstory:** 
1 Please rearrange the formview:
![image](https://user-images.githubusercontent.com/61729317/120063781-3a786580-c069-11eb-8a89-a2961d5f5983.png)

2 Please separate Date, Start, End into three columns.
![image](https://user-images.githubusercontent.com/61729317/120063940-094c6500-c06a-11eb-8a19-9d2876661dd1.png)

3 Please add Duration (End-Start) displayed in minutes

4 Please display "any extra time added with the "Delivered"-form-view.
![image](https://user-images.githubusercontent.com/61729317/120148600-c5339e80-c1e8-11eb-94c2-9871a2e52b1d.png)

5 (if not so yet, keep all bookings).

https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/outplacement_order_interpreter

**Development Branch name:** 
Dev-12.0-DAFA-AFC-2406_IMP_InterpreterAccountant-View

**Target Branch name:** 
https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02

**Description to the manifest:** 
Redesign of the interpreter accountant formview

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 Hours

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will check this isssue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/229 for this issue.

Here is results:
![tree_view](https://user-images.githubusercontent.com/36560391/120186934-c89f4800-c231-11eb-8f38-e869a20794ee.png)

![form_view](https://user-images.githubusercontent.com/36560391/120186950-cd63fc00-c231-11eb-8002-3e4e3aa0e6d2.png)

Note:

In Order field I've displayed Order name - Order Origin. Let me know if want only one and which one.
We can't see Additional Time in previous activities but when you will deliver new activity and fill additional time in that activity you can see it. Because in previous we didn't stored it.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Great!

**Comment by rupareliyahemangi145** [comment]
Thanks @FredrikArvas
