### ISSUE TITLE
AFC-2536 Add SmartButtons to Outplacement and Sales

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#657]
The Jira-number should be AFC-2536 not AFC-2356

**Userstory:** 
As a ServiceDesk and Accountant - I want to follow up the invoices of our outplacements

1 Please add SmartButtons to the **Outplacement**-form with links to:   (For Accounting Read + ServiceDesk1)
on the **Sales**-form (Display Amount on the Orders)  
on the **Invoices**-form (Display Amount on the Invoices)  
I think it is done here: https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/sale_outplacement

2 Please Make the Invoices-Button visible again on the Sale-form (For Accounting Read + ServiceDesk1)
I think it is done here: https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/sale_outplacement
// These buttons are not visible in my copy of the test-database, even if I add the group "Disable Dafa hide". 

3 Please Make the Order-Button visible again on the invoice-form  (For Accounting Read + ServiceDesk1)
I think it is done here: https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/sale_outplacement

**Module name:** (added by Nils or Fredrik)

**Development Branch name:** 
Dev-12.0-AFC-2356_DisplaySmartButtons

**Target Branch name:** 
here: https://github.com/vertelab/odoo-outplacement/tree/Dev-12.0-Fenix-Sprint-02/

**Description to the manifest:** 
AFC-2356 Adds smart buttons to make reconciliation easier

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 2 Hours

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've created PR https://github.com/vertelab/odoo-outplacement/pull/253 for this issue:
For now I've added only one group **DAFA accounting read**. Because didn't found **ServiceDisk1** group.
**ServiceDesk1** means which group **Support - 1st line** or **Dafa support - 1st line**?

Here is video for that:
https://www.loom.com/share/3c76f25ad8e344b49a4797f2e7118ed8

Please check it when you can and let me know if anything.

Thanks.

Regards,
Hemangi.
