### ISSUE TITLE
AFC-2538 Improvements in interpreter delivery

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#659]
**Userstory:** 

1 Truncate decimals in Duration
![image](https://user-images.githubusercontent.com/61729317/123328307-bae09800-d53b-11eb-9088-0c18d2eeb6d1.png)

2 If simple, please make "Count" default
![image](https://user-images.githubusercontent.com/61729317/123328477-e6fc1900-d53b-11eb-8f5b-cb3712114bb3.png)

3 Please display a red text on the kanban if the interpreter is not delivered. If possible, link directly to the "Deliver-form".
![image](https://user-images.githubusercontent.com/61729317/123329144-c54f6180-d53c-11eb-9944-c868745672e3.png)

4 Please hide or fill the "Breadcrumb" with relevant content.
![image](https://user-images.githubusercontent.com/61729317/123329378-06477600-d53d-11eb-8558-d78d500988cf.png)

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 1 Hour and 10 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

I've added new commit https://github.com/vertelab/odoo-outplacement/pull/248/commits/68008d40395330d3a7faa58c32fd324e5154c269 for this issue in PR https://github.com/vertelab/odoo-outplacement/pull/248.

I've skipped Point 2 because didn't found way for it.

Here is video for this issue:
https://www.loom.com/share/badf103c2a9741aa93ce964685a96efb

Please check it when you can and let me know if anything.

Thanks.

Regards,
Hemangi.
