### ISSUE TITLE
AFC-2433 - remove "logout" when printing a pdf in DAFA

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odoo-af#662]
**Userstory:** 
As a user, I do not want to be logged out when I print a PDF from DAFA.

**Bugreport:** (only for Bug-Issues)
Login with any user. 
Go to Invoice
Print Invoice

The same is when we print a Final Report.

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 50 mins

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

This issue may be because of System parameters. In local system with DAFA restored db I am not able to reproduce.
Turn the developer mode on where you are facing this issue.Go to Settings>>Technical>>System Parameters.
Search for "report.url" and "web.base.url". Check these. These should match URL of your Odoo instance.

**Comment by fredrikarvas-vertel** [comment]
Thanks I will try this

**Comment by fredrikarvas-vertel** [comment]
Hi

I have now tested with the following settings: 

Any suggestions?


1 
**Start:** 
web.base.url: = https://dafa-db1622.arbetsformedlingen.se (same as the site)
report.url=  http://0.0.0.0:8069
**Result:** 
The PDF prints nicely. But the user gets logged out: 

2
**Start:** 
web.base.url: = https://dafa-db1622.arbetsformedlingen.se (same as the site)
report.url=  https://dafa-db1622.arbetsformedlingen.se (same as the site)
**Result:** 
Error:
The proxy server received an invalid
response from an upstream server.
The proxy server could not handle the request POST /report/download.

undefined

3
**Start:** 
web.base.url: = https://dafa-db1622.arbetsformedlingen.se (same as the site)
report.url=  https://dafa-db1622.arbetsformedlingen.se:**8069**
**Result:** 
Error:
The proxy server received an invalid
response from an upstream server.
The proxy server could not handle the request POST /report/download.

undefined

4
Start:
web.base.url: = https://dafa-db1622.arbetsformedlingen.se (same as the site)
report.url= http://dafa-db1622.arbetsformedlingen.se:**8069** (http only)
Result:
Error:
The proxy server received an invalid
response from an upstream server.
The proxy server could not handle the request POST /report/download.

undefined



5
Start:
web.base.url: = https://dafa-db1622.arbetsformedlingen.se (same as the site)
report.url= http://dafa-db1622.arbetsformedlingen.se (http only)
Result:
Error:
The proxy server received an invalid
response from an upstream server.
The proxy server could not handle the request POST /report/download.

undefined

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Let me check about errors. I will get back to you soon.

**Comment by rupareliyahemangi145** [comment]
Hi @FredrikArvas 

I checked about this error and after some research I found that this cause may be because of  Proxy server configuration.
When printing pdf report there is time out issue, so I think we have to try by increasing time limit. 

Please check following blogs and if possible please try to increase time limit as shown in following blog and then test again after restarting odoo service and refresh browser. 
https://ubiq.co/tech-blog/increase-request-timeout-nginx/
https://ubiq.co/tech-blog/increase-request-timeout-apache/

Thanks.

Regards,
Hemangi.

**Comment by fredrikarvas-vertel** [comment]
Robin added: 

Verified in dafa-db1622 test. Add the following to hostAliases for our deployment in Openshift.

         - hostnames:
             - dafa-db1042-test.local
             - dafa-db1701-test.local
             - dafa-db823-test.local
             - dafa-test.local
           ip: 127.0.0.1
Then we can set the system parameter report.url to each domain in the databases. 
For dafa-db1042 test, report.url is 
http: //dafa-db1042-test.local: 8069
